#! /bin/sh
ssh root@meteorfood.com << EOF
                            cd /var/www/meteor;
                            echo "Starting";
                            git pull;
                            echo "Pulled";
                            ./restart;
                            echo "Restarted";

                          EOF
