version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: rails.dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    volumes:
      - /postgres_data:/var/lib/postgresql/data
    restart: always
  front:
    build:
      context: .
      dockerfile: front.dockerfile
    volumes:
      - front-volume:/meteor-frontend
  nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
            - "8000:8000"
            - "443:443"
            - "80:80"
      depends_on:
        - api
      restart: always

volumes:
  ? front-volume
