version: "3.7"
volumes:
  postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: rails.dockerfile
    depends_on:
      - db
    ports:
      - 3001:3001
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  front:
    build:
      context: .
      dockerfile: front.dockerfile
    # volumes:
    #   - front-volume:/locmerge-frontend
#  nginx:
#      image: nginx
#      volumes:
#        - ./nginx.conf:/etc/nginx/nginx.conf
#        - front-volume:/locmerge-frontend
#      ports:
#        - "8000:8000"
#      depends_on:
#        - mongo
#        - front
#        - flask
#        - kombu
#      restart: always

networks:
  ? dbnet

# volumes:
#   ? front-volume
