version: "3.7"
volumes:
  postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: rails.dockerfile
    depends_on:
      - db
    ports:
      - 3001:3001
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  front:
    build:
      context: .
      dockerfile: front.dockerfile
    # volumes:
    #   - front-volume:/locmerge-frontend

networks:
  ? dbnet

# volumes:
#   ? front-volume
