version: "3.7"

services:
  rails:
    build:
      context: .
      dockerfile: rails.dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    volumes:
      - /postgres_data:/var/lib/postgresql/data
    restart: always
  front:
    build:
      context: .
      dockerfile: front.dockerfile
    volumes:
      - front-volume:/meteor-frontend
  https-portal:
      image: steveltn/https-portal:1.7
      ports:
        - "80:80"
        - "443:443"
      links:
        - rails
      depends_on:
        - nginx
      restart: always
      environment:
        DOMAINS: "meteorfood.com -> http://nginx:8000, meteorfood.kz -> http://nginx:8000"
        STAGE: "staging"
  nginx:
        image: nginx
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - front-volume:/meteor-frontend
        depends_on:
          - rails
        restart: always

volumes:
  ? front-volume
