#! /bin/sh
docker-compose up -d --build
docker-compose run api rails db:create
docker-compose run api rails db:migrate
docker kill $(docker ps -a -f name=api_run -q)
docker rm $(docker ps -a -f name=api_run -q)
