GET http://localhost:3000/users/sign_up
Accept: application/json
Content-Type: application/json

###

GET http://localhost:3000/users/sign_in
Accept: application/json
Content-Type: application/json

###
GET http://localhost:3001/orders?not_adopted
Accept: application/json
Content-Type: application/json

###
