#! /bin/sh
docker-compose build api
docker-compose build front
docker-compose down -v
docker-compose up -d
docker-compose run api rails db:create
docker-compose run api rails db:migrate
docker kill $(docker ps -a -f name=api_run -q)
docker rm $(docker ps -a -f name=api_run -q)
