#! /bin/sh
deployerfile="deployerfile.name"
k=0
if [ -f $deployerfile ]; then
    echo "$(cat $deployerfile) is currently trying to deploy"
    echo "exiting..."
else
    echo $1 > $deployerfile
    k=1
    docker-compose build api
    docker-compose build --no-cache front
    docker-compose down -v
    docker-compose up -d
    docker-compose run api rails db:create
    docker-compose run api rails db:migrate
    docker kill $(docker ps -a -f name=api_run -q)
    docker rm $(docker ps -a -f name=api_run -q)
fi

if [ $k = 1 ]; then
    rm $deployerfile
fi