#! /bin/sh
ssh meteor@meteorfood.com -p 922 << EOF
                                    cd /var/www/meteor;
                                    docker-compose down;
                                    EOF